### PR TITLE
hot fix for forward diff issue 706

### PR DESCRIPTION
**Pull request by bvdmitri**
This PR implements a small hot-fix for https://github.com/JuliaDiff/ForwardDiff.jl/issues/706

### CODE REVIEW

**Comment by bvdmitri** [comment]
It's technically still broken, but covers at least the most common use case with `Float64`

**Comment by Nimrais** [comment]
Yeah, but we can just remove forwarddiff from the MLE.

**Comment by Nimrais** [comment]
I see no reason why the ForwardDiff is used there, and probably there should be a test for this change to fail

**Comment by bvdmitri** [comment]
> Yeah, but we can just remove forwarddiff from the MLE.

You're right, but I would not say "just" in this context :D It's quite some work and ForwardDiff actually works pretty fast as for now, this hot-fix allows us to proceed further. We can drop the dependency on ForwardDiff later since its not as easy as this patch

**Comment by Nimrais** [comment]
ok

**Review by Nimrais — APPROVED** [review]

**Comment by bvdmitri** [comment]
But I'm up to removing `ForwardDiff` from MLE indeed, it would be much better

**Comment by bvdmitri** [comment]
I've added a test for this

**Pull request merged**
